---
- name: Check if nginx packages are installed
  shell: "apt list --installed 2>/dev/null | grep nginx"
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: nginx_packages

- name: Remove nginx packages
  apt:
    name: "*nginx*"
    state: absent
    autoremove: yes
  when: nginx_packages.rc == 0

- name: Add nginx signing key
  apt_key:
    url: "https://nginx.org/keys/nginx_signing.key"
    state: present

- name: Add nginx repository into sources list
  apt_repository:
    repo: "deb [arch=amd64] http://nginx.org/packages/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} nginx"
    state: present
    filename: "nginx"
    mode: 0644

- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
